# -*- coding: utf-8 -*-
"""prework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/dtcampbellHU/93518a62cccc589ea1e1baad783a3534/prework.ipynb
"""



"""# **Data Science Prework **

*Dee Campbell*
"""

print ('Hello Black World')
print ("Dee Cee")